package cliente;

import javax.swing.JOptionPane;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.rmi.Naming;
import middleware.Interface;

public class ProvaCliente extends javax.swing.JFrame {

    /**
     * Creates new form ProvaCliente
     */
    public ProvaCliente() {
        initComponents();
    }
    
    private int nota = 0;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        questao1 = new javax.swing.ButtonGroup();
        questao2 = new javax.swing.ButtonGroup();
        questao3 = new javax.swing.ButtonGroup();
        questao4 = new javax.swing.ButtonGroup();
        questao5 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        q1A = new javax.swing.JRadioButton();
        q1B = new javax.swing.JRadioButton();
        q1C = new javax.swing.JRadioButton();
        q1D = new javax.swing.JRadioButton();
        q1E = new javax.swing.JRadioButton();
        btnLimparQ1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        q2A = new javax.swing.JRadioButton();
        q2B = new javax.swing.JRadioButton();
        q2C = new javax.swing.JRadioButton();
        q2D = new javax.swing.JRadioButton();
        q2E = new javax.swing.JRadioButton();
        btnLimparQ2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        q3A = new javax.swing.JRadioButton();
        q3B = new javax.swing.JRadioButton();
        q3C = new javax.swing.JRadioButton();
        q3D = new javax.swing.JRadioButton();
        q3E = new javax.swing.JRadioButton();
        btnLimparQ3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        q4A = new javax.swing.JRadioButton();
        q4B = new javax.swing.JRadioButton();
        q4C = new javax.swing.JRadioButton();
        q4D = new javax.swing.JRadioButton();
        q4E = new javax.swing.JRadioButton();
        btnLimparQ4 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        q5A = new javax.swing.JRadioButton();
        q5B = new javax.swing.JRadioButton();
        q5C = new javax.swing.JRadioButton();
        q5D = new javax.swing.JRadioButton();
        q5E = new javax.swing.JRadioButton();
        btnLimparQ5 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        btnEnviar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Nome: ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNome)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setText("Com qual letra começa a palavra \"AMOR\" ?");

        questao1.add(q1A);
        q1A.setText("A");
        q1A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q1AActionPerformed(evt);
            }
        });

        questao1.add(q1B);
        q1B.setText("B");
        q1B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q1BActionPerformed(evt);
            }
        });

        questao1.add(q1C);
        q1C.setText("C");

        questao1.add(q1D);
        q1D.setText("D");
        q1D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q1DActionPerformed(evt);
            }
        });

        questao1.add(q1E);
        q1E.setText("E");

        btnLimparQ1.setText("LIMPAR");
        btnLimparQ1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparQ1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(q1A)
                .addGap(18, 18, 18)
                .addComponent(q1B)
                .addGap(18, 18, 18)
                .addComponent(q1C)
                .addGap(18, 18, 18)
                .addComponent(q1D)
                .addGap(18, 18, 18)
                .addComponent(q1E)
                .addGap(18, 18, 18)
                .addComponent(btnLimparQ1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q1A)
                    .addComponent(q1B)
                    .addComponent(q1C)
                    .addComponent(q1D)
                    .addComponent(q1E)
                    .addComponent(btnLimparQ1))
                .addGap(0, 16, Short.MAX_VALUE))
        );

        jLabel2.setText("Questão 1:");

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel5.setText("Com qual letra começa a palavra \"BOLA\" ?");

        questao2.add(q2A);
        q2A.setText("A");
        q2A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q2AActionPerformed(evt);
            }
        });

        questao2.add(q2B);
        q2B.setText("B");
        q2B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q2BActionPerformed(evt);
            }
        });

        questao2.add(q2C);
        q2C.setText("C");
        q2C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q2CActionPerformed(evt);
            }
        });

        questao2.add(q2D);
        q2D.setText("D");

        questao2.add(q2E);
        q2E.setText("E");

        btnLimparQ2.setText("LIMPAR");
        btnLimparQ2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparQ2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(q2A)
                        .addGap(18, 18, 18)
                        .addComponent(q2B)
                        .addGap(18, 18, 18)
                        .addComponent(q2C)
                        .addGap(18, 18, 18)
                        .addComponent(q2D)
                        .addGap(18, 18, 18)
                        .addComponent(q2E)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimparQ2)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q2A)
                    .addComponent(q2B)
                    .addComponent(q2C)
                    .addComponent(q2D)
                    .addComponent(q2E)
                    .addComponent(btnLimparQ2))
                .addGap(0, 32, Short.MAX_VALUE))
        );

        jLabel4.setText("Questão 2:");

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel7.setText("Com qual letra começa a palavra \"CEBOLA\" ?");

        questao3.add(q3A);
        q3A.setText("A");

        questao3.add(q3B);
        q3B.setText("B");

        questao3.add(q3C);
        q3C.setText("C");

        questao3.add(q3D);
        q3D.setText("D");

        questao3.add(q3E);
        q3E.setText("E");

        btnLimparQ3.setText("LIMPAR");
        btnLimparQ3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparQ3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(q3A)
                        .addGap(18, 18, 18)
                        .addComponent(q3B)
                        .addGap(18, 18, 18)
                        .addComponent(q3C)
                        .addGap(18, 18, 18)
                        .addComponent(q3D)
                        .addGap(18, 18, 18)
                        .addComponent(q3E)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimparQ3)))
                .addGap(0, 17, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q3A)
                    .addComponent(q3B)
                    .addComponent(q3C)
                    .addComponent(q3D)
                    .addComponent(q3E)
                    .addComponent(btnLimparQ3))
                .addGap(0, 32, Short.MAX_VALUE))
        );

        jLabel6.setText("Questão 3:");

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel10.setText("Com qual letra começa a palavra \"DADO\" ?");

        questao4.add(q4A);
        q4A.setText("A");

        questao4.add(q4B);
        q4B.setText("B");

        questao4.add(q4C);
        q4C.setText("C");

        questao4.add(q4D);
        q4D.setText("D");

        questao4.add(q4E);
        q4E.setText("E");

        btnLimparQ4.setText("LIMPAR");
        btnLimparQ4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparQ4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(q4A)
                        .addGap(18, 18, 18)
                        .addComponent(q4B)
                        .addGap(18, 18, 18)
                        .addComponent(q4C)
                        .addGap(18, 18, 18)
                        .addComponent(q4D)
                        .addGap(18, 18, 18)
                        .addComponent(q4E)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimparQ4)))
                .addGap(0, 17, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q4A)
                    .addComponent(q4B)
                    .addComponent(q4C)
                    .addComponent(q4D)
                    .addComponent(q4E)
                    .addComponent(btnLimparQ4))
                .addGap(0, 61, Short.MAX_VALUE))
        );

        jLabel8.setText("Questão 4: ");

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel11.setText("Com qual letra começa a palavra \"ESCOLA\" ?");

        questao5.add(q5A);
        q5A.setText("A");

        questao5.add(q5B);
        q5B.setText("B");

        questao5.add(q5C);
        q5C.setText("C");

        questao5.add(q5D);
        q5D.setText("D");

        questao5.add(q5E);
        q5E.setText("E");

        btnLimparQ5.setText("LIMPAR");
        btnLimparQ5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparQ5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(q5A)
                        .addGap(18, 18, 18)
                        .addComponent(q5B)
                        .addGap(18, 18, 18)
                        .addComponent(q5C)
                        .addGap(18, 18, 18)
                        .addComponent(q5D)
                        .addGap(18, 18, 18)
                        .addComponent(q5E)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimparQ5)))
                .addGap(0, 17, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q5A)
                    .addComponent(q5B)
                    .addComponent(q5C)
                    .addComponent(q5D)
                    .addComponent(q5E)
                    .addComponent(btnLimparQ5))
                .addGap(0, 61, Short.MAX_VALUE))
        );

        jLabel9.setText("Questão 5:");

        btnEnviar.setText("ENVIAR");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2)
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6)
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(btnEnviar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEnviar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void q1BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q1BActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q1BActionPerformed

    private void q1DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q1DActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q1DActionPerformed

    private void q2BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q2BActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q2BActionPerformed

    private void q2CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q2CActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q2CActionPerformed

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        //Associando respostas a cada botão
        q1A.setActionCommand("A");
        q2A.setActionCommand("A");
        q3A.setActionCommand("A");
        q4A.setActionCommand("A");
        q5A.setActionCommand("A");
        q1B.setActionCommand("B");
        q2B.setActionCommand("B");
        q3B.setActionCommand("B");
        q4B.setActionCommand("B");
        q5B.setActionCommand("B");
        q1C.setActionCommand("C");
        q2C.setActionCommand("C");
        q3C.setActionCommand("C");
        q4C.setActionCommand("C");
        q5C.setActionCommand("C");
        q1D.setActionCommand("D");
        q2D.setActionCommand("D");
        q3D.setActionCommand("D");
        q4D.setActionCommand("D");
        q5D.setActionCommand("D");
        q1E.setActionCommand("E");
        q2E.setActionCommand("E");
        q3E.setActionCommand("E");
        q4E.setActionCommand("E");
        q5E.setActionCommand("E");
        // -------------------------------
        
        //Armazenando respostas no arquivo txt          
        String resposta ="";        
        File arquivo = new File("src/cliente/prova.txt");
        
        try {
            arquivo.createNewFile();
            PrintWriter escritor = new PrintWriter(arquivo);
                                   
            if(questao1.getSelection() == null) resposta = "1-X\n";
            else resposta = "1-" + questao1.getSelection().getActionCommand() + "\n";
            
            if(questao2.getSelection() == null) resposta += "2-X\n";
            else resposta += ("2-" + questao2.getSelection().getActionCommand() + "\n");
            
            if(questao3.getSelection() == null) resposta += "3-X\n";
            else resposta += ("3-" + questao3.getSelection().getActionCommand() + "\n");
            
            if(questao4.getSelection() == null) resposta += "4-X\n";
            else resposta += ("4-" + questao4.getSelection().getActionCommand() + "\n");
            
            if(questao5.getSelection() == null) resposta += "5-X";
            else resposta += ("5-" + questao5.getSelection().getActionCommand());
                                               
            escritor.append(resposta);
            escritor.close();
            
            System.out.println("Arquivo gravado");
        
        } catch (Exception e) {
            e.printStackTrace();
        }
        // -------------------------------
        
        // Enviando txt para o servidor
        try {
            System.out.println("Enviando arquivo...");
            Interface objRemoto = (Interface) Naming.lookup("rmi://192.168.100.22/URLProva");
            FileInputStream buffEntrada = new FileInputStream(arquivo);
            byte[] dados = new byte[1024 * 1024];
            int tamanho = buffEntrada.read(dados);
            
            while(tamanho > 0){
                this.nota = objRemoto.rodar(txtNome.getText(), "src/servidor/prova", dados, tamanho);
                tamanho = buffEntrada.read(dados);
            }
            
            System.out.println("Arquivo enviado !");
            
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        //------------------------------
        
                                                        
        // Mostrando suas respostas + nota
        JOptionPane.showMessageDialog(null, "Suas respostas foram: " + "\n" + resposta
                + "\nSua nota foi = " + this.nota);

        this.dispose();
    }//GEN-LAST:event_btnEnviarActionPerformed

    private void q2AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q2AActionPerformed
        
    }//GEN-LAST:event_q2AActionPerformed

    private void q1AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q1AActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q1AActionPerformed

    private void btnLimparQ1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparQ1ActionPerformed
        questao1.clearSelection();
    }//GEN-LAST:event_btnLimparQ1ActionPerformed

    private void btnLimparQ2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparQ2ActionPerformed
        questao2.clearSelection();
    }//GEN-LAST:event_btnLimparQ2ActionPerformed

    private void btnLimparQ3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparQ3ActionPerformed
        questao3.clearSelection();
    }//GEN-LAST:event_btnLimparQ3ActionPerformed

    private void btnLimparQ4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparQ4ActionPerformed
        questao4.clearSelection();
    }//GEN-LAST:event_btnLimparQ4ActionPerformed

    private void btnLimparQ5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparQ5ActionPerformed
        questao5.clearSelection();
    }//GEN-LAST:event_btnLimparQ5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProvaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProvaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProvaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProvaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProvaCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviar;
    private javax.swing.JButton btnLimparQ1;
    private javax.swing.JButton btnLimparQ2;
    private javax.swing.JButton btnLimparQ3;
    private javax.swing.JButton btnLimparQ4;
    private javax.swing.JButton btnLimparQ5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JRadioButton q1A;
    private javax.swing.JRadioButton q1B;
    private javax.swing.JRadioButton q1C;
    private javax.swing.JRadioButton q1D;
    private javax.swing.JRadioButton q1E;
    private javax.swing.JRadioButton q2A;
    private javax.swing.JRadioButton q2B;
    private javax.swing.JRadioButton q2C;
    private javax.swing.JRadioButton q2D;
    private javax.swing.JRadioButton q2E;
    private javax.swing.JRadioButton q3A;
    private javax.swing.JRadioButton q3B;
    private javax.swing.JRadioButton q3C;
    private javax.swing.JRadioButton q3D;
    private javax.swing.JRadioButton q3E;
    private javax.swing.JRadioButton q4A;
    private javax.swing.JRadioButton q4B;
    private javax.swing.JRadioButton q4C;
    private javax.swing.JRadioButton q4D;
    private javax.swing.JRadioButton q4E;
    private javax.swing.JRadioButton q5A;
    private javax.swing.JRadioButton q5B;
    private javax.swing.JRadioButton q5C;
    private javax.swing.JRadioButton q5D;
    private javax.swing.JRadioButton q5E;
    private javax.swing.ButtonGroup questao1;
    private javax.swing.ButtonGroup questao2;
    private javax.swing.ButtonGroup questao3;
    private javax.swing.ButtonGroup questao4;
    private javax.swing.ButtonGroup questao5;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
